using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Eshava.Storm.MetaData.Enums;

namespace Eshava.Storm.MetaData.Models
{
	internal class Entity : AbstractEntity
	{
		internal Entity(Type type, ConfigurationSource configurationSource) : base(type, configurationSource)
		{

		}

		public string TableName { get; private set; }

		public void SetTableName(string tableName)
		{
			TableName = tableName;
		}

		public bool HasPrimaryKey()
		{
			return Properties.Values.Any(p => p.IsPrimaryKey);
		}

		public bool HasAutoGeneratedPrimaryKey()
		{
			var primaryKeys = Properties.Values.Where(p => p.IsPrimaryKey && p.AutoGeneratedOption != DatabaseGeneratedOption.None);

			return primaryKeys.Count() == 1;
		}

		public Property GetFirstPrimaryKey()
		{
			return Properties.Values.First(p => p.IsPrimaryKey);
		}
	}}