using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;
using Eshava.Storm.Attributes;

namespace Eshava.Storm.Extensions
{
	internal static class PropertyInfoExtensions
	{
		internal static bool IsOwnsOne(this PropertyInfo propertyInfo)
		{
			return propertyInfo != null
				&& propertyInfo.GetCustomAttribute<OwnsOneAttribute>() != default;
		}

		internal static string GetColumnName(this PropertyInfo propertyInfo)
		{
			var column = propertyInfo.GetCustomAttribute<ColumnAttribute>();
			if (column != default)
			{
				return column.Name;
			}

			return propertyInfo.Name;
		}

		internal static bool IsAutoGenerated(this PropertyInfo propertyInfo)
		{
			var databaseGenerated = propertyInfo.GetCustomAttribute<DatabaseGeneratedAttribute>();
			if (databaseGenerated != default && databaseGenerated.DatabaseGeneratedOption != DatabaseGeneratedOption.None)
			{
				return true;
			}

			return false;
		}

		internal static bool IsPrímaryKey(this PropertyInfo propertyInfo)
		{
			return propertyInfo.GetCustomAttribute<KeyAttribute>() != default;
		}
	}
}