using System.Reflection;

namespace Eshava.Storm.Models
{
	internal class KeyProperty
	{
		public PropertyInfo PropertyInfo { get; set; }
		public bool AutoGenerated { get; set; }
		public string ColumnName { get; set; }
	}
}